// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeIons(arg1) {
  return window['go']['app']['App']['AnalyzeIons'](arg1);
}

export function BalanceEquation(arg1) {
  return window['go']['app']['App']['BalanceEquation'](arg1);
}

export function BalanceIonEquation(arg1) {
  return window['go']['app']['App']['BalanceIonEquation'](arg1);
}

export function GetAllElements() {
  return window['go']['app']['App']['GetAllElements']();
}

export function GetElement(arg1) {
  return window['go']['app']['App']['GetElement'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['app']['App']['GetSetting'](arg1);
}

export function ListPlugins() {
  return window['go']['app']['App']['ListPlugins']();
}

export function ListProviders() {
  return window['go']['app']['App']['ListProviders']();
}

export function ParseFormula(arg1) {
  return window['go']['app']['App']['ParseFormula'](arg1);
}

export function ParseIon(arg1) {
  return window['go']['app']['App']['ParseIon'](arg1);
}

export function ProcessEquation(arg1) {
  return window['go']['app']['App']['ProcessEquation'](arg1);
}

export function RenderEquation(arg1) {
  return window['go']['app']['App']['RenderEquation'](arg1);
}

export function RenderFormula(arg1) {
  return window['go']['app']['App']['RenderFormula'](arg1);
}

export function SearchCompoundOnline(arg1) {
  return window['go']['app']['App']['SearchCompoundOnline'](arg1);
}

export function SearchCompounds(arg1) {
  return window['go']['app']['App']['SearchCompounds'](arg1);
}

export function SearchElements(arg1) {
  return window['go']['app']['App']['SearchElements'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['app']['App']['SetSetting'](arg1, arg2);
}

export function TestProviderConnection(arg1) {
  return window['go']['app']['App']['TestProviderConnection'](arg1);
}
