// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chemistry} from '../models';
import {plugin} from '../models';
import {provider} from '../models';

export function AnalyzeIons(arg1:string):Promise<chemistry.IonicEquationResult>;

export function BalanceEquation(arg1:string):Promise<chemistry.BalanceResult>;

export function BalanceIonEquation(arg1:string):Promise<chemistry.BalanceResult>;

export function GetAllElements():Promise<any>;

export function GetElement(arg1:string):Promise<any>;

export function GetSetting(arg1:string):Promise<string>;

export function ListPlugins():Promise<Array<plugin.Plugin>>;

export function ListProviders():Promise<Array<provider.Provider>>;

export function ParseFormula(arg1:string):Promise<chemistry.FormulaResult>;

export function ParseIon(arg1:string):Promise<chemistry.Ion>;

export function ProcessEquation(arg1:string):Promise<Record<string, any>>;

export function RenderEquation(arg1:string):Promise<chemistry.RenderResult>;

export function RenderFormula(arg1:string):Promise<chemistry.RenderResult>;

export function SearchCompoundOnline(arg1:string):Promise<Array<provider.CompoundInfo>>;

export function SearchCompounds(arg1:string):Promise<any>;

export function SearchElements(arg1:string):Promise<any>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function TestProviderConnection(arg1:string):Promise<string>;
