// Wails Go bindings - these will be auto-generated by Wails build.
// For development without Wails, we provide mock implementations.

declare global {
  interface Window {
    go: {
      app: {
        ParseFormula: (formula: string) => Promise<any>
        BalanceEquation: (equation: string) => Promise<any>
        ProcessEquation: (equation: string) => Promise<any>
        AnalyzeIons: (equation: string) => Promise<any>
        BalanceIonEquation: (equation: string) => Promise<any>
        ParseIon: (ionStr: string) => Promise<any>
        RenderFormula: (formula: string) => Promise<any>
        RenderEquation: (equation: string) => Promise<any>
        GetElement: (symbol: string) => Promise<any>
        SearchElements: (query: string) => Promise<any>
        SearchCompounds: (query: string) => Promise<any>
        ListProviders: () => Promise<any>
        SearchCompoundOnline: (query: string) => Promise<any>
        TestProviderConnection: (name: string) => Promise<any>
        ListPlugins: () => Promise<any>
        SetPluginEnabled: (name: string, enabled: boolean) => Promise<any>
        GetSetting: (key: string) => Promise<any>
        SetSetting: (key: string, value: string) => Promise<any>
      }
    }
  }
}

// Check if running inside Wails
function isWails(): boolean {
  return typeof window !== 'undefined' && !!window.go?.app
}

// Formula API
export async function parseFormula(formula: string) {
  if (isWails()) return window.go.app.ParseFormula(formula)
  return mockParseFormula(formula)
}

export async function balanceEquation(equation: string) {
  if (isWails()) return window.go.app.BalanceEquation(equation)
  return mockBalanceEquation(equation)
}

export async function processEquation(equation: string) {
  if (isWails()) return window.go.app.ProcessEquation(equation)
  return mockProcessEquation(equation)
}

export async function analyzeIons(equation: string) {
  if (isWails()) return window.go.app.AnalyzeIons(equation)
  return mockAnalyzeIons(equation)
}

export async function balanceIonEquation(equation: string) {
  if (isWails()) return window.go.app.BalanceIonEquation(equation)
  return mockBalanceEquation(equation)
}

export async function parseIon(ionStr: string) {
  if (isWails()) return window.go.app.ParseIon(ionStr)
  return { formula: ionStr, symbol: ionStr, charge: 0, isCation: false }
}

export async function renderFormula(formula: string) {
  if (isWails()) return window.go.app.RenderFormula(formula)
  return { latex: `\\ce{${formula}}`, markdown: formula, html: formula, unicode: formula }
}

export async function renderEquation(equation: string) {
  if (isWails()) return window.go.app.RenderEquation(equation)
  return { latex: `\\ce{${equation}}`, markdown: equation, html: equation, unicode: equation }
}

export async function getElement(symbol: string) {
  if (isWails()) return window.go.app.GetElement(symbol)
  return null
}

export async function searchElements(query: string) {
  if (isWails()) return window.go.app.SearchElements(query)
  return []
}

export async function searchCompounds(query: string) {
  if (isWails()) return window.go.app.SearchCompounds(query)
  return []
}

export async function listProviders() {
  if (isWails()) return window.go.app.ListProviders()
  return []
}

export async function searchCompoundOnline(query: string) {
  if (isWails()) return window.go.app.SearchCompoundOnline(query)
  return []
}

export async function testProviderConnection(name: string) {
  if (isWails()) return window.go.app.TestProviderConnection(name)
  return 'Not connected (dev mode)'
}

export async function listPlugins() {
  if (isWails()) return window.go.app.ListPlugins()
  return []
}

export async function setPluginEnabled(name: string, enabled: boolean) {
  if (isWails()) return window.go.app.SetPluginEnabled(name, enabled)
  return null
}

export async function getSetting(key: string) {
  if (isWails()) return window.go.app.GetSetting(key)
  return ''
}

export async function setSetting(key: string, value: string) {
  if (isWails()) return window.go.app.SetSetting(key, value)
  return null
}

// ============================================================
// Mock implementations for dev mode (no Wails runtime)
// ============================================================

function mockParseFormula(formula: string) {
  const elements: Record<string, number> = {}
  const masses: Record<string, number> = {
    H: 1.008, He: 4.003, Li: 6.941, Be: 9.012, B: 10.81, C: 12.011,
    N: 14.007, O: 15.999, F: 18.998, Ne: 20.18, Na: 22.99, Mg: 24.305,
    Al: 26.982, Si: 28.086, P: 30.974, S: 32.065, Cl: 35.453, Ar: 39.948,
    K: 39.098, Ca: 40.078, Fe: 55.845, Cu: 63.546, Zn: 65.38, Ag: 107.87,
    Au: 196.97, Hg: 200.59, Pb: 207.2, Mn: 55.938, Cr: 51.996, Ni: 58.693,
    Ba: 137.33, Sr: 87.62, Br: 79.904, I: 126.9,
  }

  let mw = 0
  const stack: [Record<string, number>, number][] = []
  let current: Record<string, number> = {}
  let i = 0

  while (i < formula.length) {
    const ch = formula[i]
    if (ch === '(' || ch === '[') {
      stack.push([current, 0])
      current = {}
      i++
    } else if (ch === ')' || ch === ']') {
      i++
      let num = ''
      while (i < formula.length && formula[i] >= '0' && formula[i] <= '9') {
        num += formula[i]; i++
      }
      const mult = num ? parseInt(num) : 1
      const [prev] = stack.pop()!
      for (const [elem, cnt] of Object.entries(current)) {
        prev[elem] = (prev[elem] || 0) + cnt * mult
      }
      current = prev
    } else if (ch >= 'A' && ch <= 'Z') {
      let elem = ch; i++
      while (i < formula.length && formula[i] >= 'a' && formula[i] <= 'z') {
        elem += formula[i]; i++
      }
      let num = ''
      while (i < formula.length && formula[i] >= '0' && formula[i] <= '9') {
        num += formula[i]; i++
      }
      const count = num ? parseInt(num) : 1
      current[elem] = (current[elem] || 0) + count
    } else {
      i++
    }
  }

  for (const [elem, count] of Object.entries(current)) {
    elements[elem] = count
    mw += (masses[elem] || 0) * count
  }

  return {
    original: formula,
    elements,
    molecularWeight: Math.round(mw * 1000) / 1000,
    subscript: toSubscript(formula),
    latex: `\\ce{${formula}}`,
    isValid: true,
  }
}

function toSubscript(s: string): string {
  const sub: Record<string, string> = {
    '0': '₀', '1': '₁', '2': '₂', '3': '₃', '4': '₄',
    '5': '₅', '6': '₆', '7': '₇', '8': '₈', '9': '₉',
  }
  let result = ''
  for (const ch of s) {
    result += sub[ch] || ch
  }
  return result
}

function mockBalanceEquation(equation: string) {
  return {
    original: equation,
    balanced: equation,
    coefficients: [],
    isBalanced: false,
    elements: [],
    subscript: equation,
    latex: `\\ce{${equation}}`,
    error: 'Connect Wails backend for balancing',
  }
}

function mockProcessEquation(equation: string) {
  return {
    original: equation,
    balanced: equation,
    isBalanced: false,
    subscript: equation,
    latex: `\\ce{${equation}}`,
    elements: {},
  }
}

function mockAnalyzeIons(equation: string) {
  return {
    molecular: equation,
    fullIonic: equation,
    netIonic: equation,
    spectators: [],
    chargeBalanced: true,
    reactantCharges: 0,
    productCharges: 0,
  }
}
